version: '3.6'

services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:0.3.1
    deploy:
      restart_policy:
        condition: any
        max_attempts: 5
    volumes:
    - /var/local/caddy/data:/root/.caddy
    - /var/local/caddy/www:/var/www
    - /media/Storage:/media/Storage
    - /var/.htpasswd:/var/.htpasswd
    - /var/run/docker.sock:/var/run/docker.sock
    configs:
    - source: caddyfile
      target: /Caddyfile
    networks:
    - internet
    - publicweb
    ports:
    - target: 80
      published: 80
      protocol: tcp
      mode: ingress
    - target: 443
      published: 443
      protocol: tcp
      mode: ingress
    command: -agree -email tech@urfonline.com -docker-caddyfile-path /Caddyfile -log stdout

networks:
  internet:
    driver: overlay
  publicweb:
    driver: overlay
    external: true
    internal: true

configs:
  caddyfile:
    file: ./Caddyfile
