version: '3.6'

services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:2.4.0
    deploy:
      labels:
        caddy.email: tech@urfonline.com
      restart_policy:
        condition: any
        max_attempts: 5
    volumes:
    - /var/local/caddy/data:/root/.caddy
    - /var/local/caddy/www:/var/www
    - /media/Storage:/media/Storage
    - /var/run/docker.sock:/var/run/docker.sock
    configs:
    - source: caddyfile
      target: /Caddyfile
    environment:
    - CADDY_INGRESS_NETWORKS=publicweb
    networks:
    - internet
    - publicweb
    ports:
    - target: 80
      published: 80
      protocol: tcp
      mode: host
    - target: 443
      published: 443
      protocol: tcp
      mode: host

networks:
  internet:
    driver: overlay
  publicweb:
    driver: overlay
    external: true
    internal: true

configs:
  caddy-file:
    file: ./Caddyfile
    labels:
      caddy:
