version: '3.6'

services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:0.3.1
    deploy:
      restart-policy:
        condition: any
        max_attempts: 5
    volumes:
    - /var/local/caddy:/root/.caddy
    - /var/.htpasswd:/var/.htpasswd
    - /media/Storage:/media/Storage
    - /var/run/docker.sock:/var/run/docker.sock
    configs:
    - caddyfile
    networks:
    - internet
    - publicweb
    ports:
    - target: 80
      published: 80
      protocol: tcp
      mode: ingress
    - target: 443
      published: 443
      protocol: tcp
      mode: ingress
    command: /bin/caddy -agree -email tech@urfonline.com -conf /Caddyfile

networks:
  internet:
    driver: overlay
  publicweb:
    driver: overlay
    external: true
    internal: true
    config:
    - subnet: 172.20.76.0/24

configs:
  caddyfile:
    file: ./Caddyfile
    name: Caddyfile
