version: '3.6'

services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:0.3.1
    volumes:
    - /var/local/caddy:/root/.caddy
    - /var/.htpasswd:/var/.htpasswd
    - /media/Storage:/media/Storage
    - /var/run/docker.sock:/var/run/docker.sock
    configs:
    - caddyfile
    networks:
    - internet
    - publicweb
    ports:
    - "80:80"
    - "443:443"
    command: /bin/caddy -agree -email tech@urfonline.com -conf /Caddyfile

networks:
  internet:
    driver: overlay
  publicweb:
    driver: overlay
    external: true
    internal: true
    config:
    - subnet: 172.20.76.0/24

configs:
  caddyfile:
    file: ./Caddyfile
    name: Caddyfile
