version: '3.7'

services:
  vaultwarden:
    image: vaultwarden/server:latest
    networks:
      - app
      - publicweb
    volumes:
      - data:/data
    environment:
      - WEBSOCKET_ENABLED=true
    env_file: vault.env
    deploy:
      restart_policy:
        condition: any
        max_attempts: 5
      labels:
        caddy: bitwarden.urfonline.com
        caddy.reverse_proxy: "{{upstreams 80}}"
        caddy.1_reverse_proxy: "/notifications/hub {{upstreams 3012}}"

networks:
  app:
    driver: overlay
    ipam:
      config:
      - subnet: 172.20.79.0/24
  publicweb:
    external: true

volumes:
  data:
