version: '3.6'

services:
  overlay:
    image: docker.pkg.github.com/urfonline/overlay/overlay:1.0.2
    volumes:
    - /etc/nodecg:/usr/src/app/cfg
    - data:/usr/src/app/db
    - logs:/usr/src/app/log
    networks:
    - app
    - publicweb
    deploy:
      labels:
        caddy: overlay.urfonline.com
        caddy.reverse_proxy: {{upstreams 9090}}

networks:
  app:
    driver: overlay
    ipam:
      config:
        - subnet: 172.20.78.0/24
  publicweb:
    external: true

volumes:
  data:
  logs:
