version: '3.6'

services:
  overlay:
    image: ghcr.io/urfonline/overlay/charity-overlay:1.0.3
    volumes:
    - /etc/nodecg:/opt/nodecg/cfg
    - data:/opt/nodecg/db
    - logs:/opt/nodecg/log
    networks:
    - app
    - publicweb
    deploy:
      labels:
        caddy: overlay.urfonline.com
        caddy.reverse_proxy: "{{upstreams 9090}}"

networks:
  app:
    driver: overlay
    ipam:
      config:
        - subnet: 172.20.78.0/24
  publicweb:
    external: true

volumes:
  data:
  logs:
