version: '3.6'

services:
  bartender:
    image: docker.pkg.github.com/urfonline/bartender/bartender:latest
    volumes:
    - /etc/bartender:/app/config
    - data:/app/data
    networks:
    - app
    - publicweb
    deploy:
      labels:
      - "caddy.address=bartender.urfonline.com"
      - "caddy.proxy.transparent"
      - "caddy.targetport=8000"

networks:
  app:
  publicweb:
    external: true

volumes:
  data:
