version: '3.6'

services:
  bartender:
    image: ghcr.io/urfonline/bartender/bartender:1.0.5
    volumes:
    - /etc/bartender:/app/config
    - data:/app/data
    networks:
    - app
    - publicweb
    deploy:
      labels:
      - "caddy.address=bartender.urfonline.com"
      - "caddy.proxy.transparent"
      - "caddy.targetport=8000"

networks:
  app:
    driver: overlay
    ipam:
      config:
      - subnet: 172.20.77.0/24
  publicweb:
    external: true

volumes:
  data:
