version: '3.6'

services:
  bartender:
    image: ghcr.io/urfonline/bartender/bartender:1.0.8
    volumes:
    - /etc/bartender:/app/config
    - data:/app/data
    networks:
    - app
    - publicweb
    deploy:
      labels:
        caddy: bartender.urfonline.com
        caddy.reverse_proxy: "{{upstreams 8000}}"

networks:
  app:
    driver: overlay
    ipam:
      config:
      - subnet: 172.20.77.0/24
  publicweb:
    external: true

volumes:
  data:
