version: '3.6'

services:
  bartender:
    image: docker.pkg.github.com/urfonline/bartender/bartender:latest
    volumes:
    - /etc/bartender:/app/config
    - data:/app/data
    ports:
    - "5000"
    networks:
    - publicweb
    deploy:
      labels:
      - "caddy.address=bartender.urfonline.com"
      - "caddy.proxy.transparent"

networks:
  publicweb:
    external: true
